commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.0.0
  version_files:
    - package_name/__init__.py:__version__
  update_changelog_on_bump: true
  bump_message: "chore(release): $current_version → $new_version [skip ci]"