# Generated by Django 4.2 on 2025-03-12 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=40)),
                ('question', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('PRIBADI', 'pribadi'), ('PENGAWASAN', 'pengawasan')], default='PRIBADI', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='tag.tag')),
            ],
            options={
                'db_table': 'question_question',
            },
        ),
    ]
