# Generated by Django 5.1.6 on 2025-03-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='content',
            new_name='question',
        ),
    ]
