# Generated by Django 5.1.6 on 2025-03-04 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_content_problem_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
