# Generated by Django 5.1.6 on 2025-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('PRIBADI', 'Pribadi'), ('PENGAWASAN', 'Pengawasan')], default='PRIBADI', max_length=10),
        ),
    ]
