# Generated by Django 5.1.6 on 2025-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
