# Generated by Django 5.1.7 on 2025-03-28 22:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("npm", models.CharField(max_length=10)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("keterangan", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["npm", "startDate", "endDate"],
                        name="blacklist_search_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("endDate__gte", datetime.date(2025, 3, 28))
                        ),
                        fields=("npm",),
                        name="unique_active_blacklist",
                    )
                ],
            },
        ),
    ]
