# Generated by Django 5.1.7 on 2025-03-30 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blacklist",
            name="unique_active_blacklist",
        ),
        migrations.AddConstraint(
            model_name="blacklist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("endDate__gte", datetime.date(2025, 3, 30))),
                fields=("npm",),
                name="unique_active_blacklist",
            ),
        ),
    ]
