# Generated by Django 5.1.7 on 2025-04-20 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0005_remove_blacklist_unique_active_blacklist_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blacklist",
            name="unique_active_blacklist",
        ),
        migrations.AddConstraint(
            model_name="blacklist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("endDate__gte", datetime.date(2025, 4, 20))),
                fields=("npm",),
                name="unique_active_blacklist",
            ),
        ),
    ]
