# Generated by Django 5.1.7 on 2025-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_custom_user_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="family_name",
            field=models.CharField(
                blank=True, help_text="User's family name (last name).", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="given_name",
            field=models.CharField(
                blank=True, help_text="User's given name (first name).", max_length=30
            ),
        ),
    ]
