# Generated by Django 5.1.7 on 2025-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_custom_user_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="angkatan",
            field=models.CharField(
                blank=True,
                help_text="Student year (angkatan).",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="noWA",
            field=models.CharField(
                blank=True, help_text="WhatsApp number.", max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="npm",
            field=models.CharField(
                blank=True,
                help_text="Student ID number from SSO UI.",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("pengguna", "Pengguna"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                ],
                default="pengguna",
                help_text="User role in the application.",
                max_length=10,
            ),
        ),
    ]
