# Generated by Django 5.1.7 on 2025-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_alter_customuser_options_alter_customuser_groups_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="noWA",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Regular User"), ("admin", "Administrator")],
                default="guest",
                help_text="User role in the application.",
                max_length=10,
            ),
        ),
    ]
