# Generated by Django 5.1.7 on 2025-04-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_customuser_nowa_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Regular User"), ("admin", "Administrator")],
                default="user",
                help_text="User role in the application.",
                max_length=10,
            ),
        ),
    ]
