# Generated by Django 4.2 on 2025-03-12 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('mode', models.CharField(choices=[('PRIBADI', 'pribadi'), ('PENGAWASAN', 'pengawasan')], default='PRIBADI', max_length=20)),
                ('cause', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('root_status', models.BooleanField(default=False)),
                ('feedback', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
