# Generated by Django 4.2 on 2025-03-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cause", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Causes",
        ),
    ]
